name: Build and Deploy

on:
  push:
    branches:
      - main
      
# 环境变量
env:
  # GitHub 用户名
  GH_USERNAME: Freedom-FJ
  # commit 时使用的 Email
  GH_EMAIL: 572031690@qq.com
  # 部署 GitHub Pages 的仓库，格式：用户名/仓库名
  GH_REPO: Freedom-FJ/572031690@qq.com
  # 部署 GitHub Pages 的仓库的分支名
  GH_BRANCH: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build site
        run: pnpm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 指定前面准备的 token
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./site/.vitepress/dist
